#!/bin/sh

# Try to run these.  If they fail, no biggie.
/usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas/ 1> /dev/null 2> /dev/null
/usr/bin/gio-querymodules /usr/lib/gio/modules/ 1> /dev/null 2> /dev/null
