#!/bin/sh
#
# /etc/rc.d/elogind: start/stop elogind daemon
#

SSD=/sbin/start-stop-daemon
PROG=/lib/elogind/elogind
PID=/run/elogind.pid
OPTS="--daemon"

case $1 in
start)
	if [ -x /lib/elogind/elogind ]; then
	  if [ ! -d /run/user ]; then
	  mkdir -p /run/user
	fi
	if [ ! -d /run/systemd ]; then
	  mkdir -p /run/elogind /sys/fs/cgroup/elogind
	  ( cd /run; rm -rf systemd; ln -sf elogind systemd; )
	  ( cd /sys/fs/cgroup; rm -rf systemd; ln -sf elogind systemd; )
	fi
	$SSD --start --pidfile $PID --exec $PROG -- $OPTS
	;;
stop)
	$SSD --stop --retry 10 --remove-pidfile $PID --exec $PROG --pidfile $PID
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	$SSD --status --exec $PROG
	case $? in
	0) echo "$PROG is running with pid $(pidof $PROG)" ;;
	1) echo "$PROG is not running but the pid file $PID exists" ;;
	3) echo "$PROG is not running" ;;
	4) echo "Unable to determine the program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|restart|status]"
	;;
esac

# End of file
